import type {
  Product,
  User,
  Review,
  InfluencerReview,
  Influencer,
} from "../types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=100&h=100&fit=crop&crop=face",
    profile: {
      skinType: "combination",
      skinTone: "medium",
      skinConcerns: ["oiliness", "large_pores"],
      ageRange: "26-35",
      preferredBrands: ["CeraVe", "The Ordinary"],
      allergies: [],
    },
  },
  {
    id: "user-2",
    name: "Michael Chen",
    email: "michael@example.com",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    profile: {
      skinType: "oily",
      skinTone: "medium",
      skinConcerns: ["acne", "oiliness"],
      ageRange: "26-35",
      preferredBrands: ["Bulldog", "Jack Black"],
      allergies: [],
    },
  },
  {
    id: "user-3",
    name: "Emma Williams",
    email: "emma@example.com",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    profile: {
      skinType: "dry",
      skinTone: "fair",
      skinConcerns: ["dryness", "sensitivity"],
      ageRange: "36-45",
      preferredBrands: ["La Roche-Posay", "Cetaphil"],
      allergies: [],
    },
  },
];

export const mockInfluencers: Influencer[] = [
  {
    id: "influencer-1",
    name: "Beauty Guru Emma",
    username: "beautyguruemma",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    bio: "Professional makeup artist and skincare enthusiast",
    followerCount: 250000,
    verificationStatus: "verified",
    platforms: [
      {
        platform: "instagram",
        username: "beautyguruemma",
        url: "https://instagram.com/beautyguruemma",
        followerCount: 150000,
      },
    ],
    specialties: ["makeup", "skincare"],
  },
];

export const mockProducts: Product[] = [
  {
    id: "product-1",
    name: "Hydrating Hyaluronic Acid Serum",
    brand: "GlowCo",
    description:
      "A powerful hydrating serum with multiple types of hyaluronic acid for all-day moisture.",
    category: "skincare",
    subcategory: "serums",
    targetGender: "unisex",
    image:
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=300&h=300&fit=crop",
    ],
    ingredients: ["Hyaluronic Acid", "Vitamin B5", "Glycerin", "Aqua"],
    suitableFor: {
      skinTypes: ["dry", "normal", "combination"],
      skinTones: ["fair", "light", "medium", "tan", "deep", "dark"],
      concerns: ["dryness", "aging"],
    },
    priceComparison: [
      {
        store: "Sephora",
        price: 42,
        currency: "EUR",
        url: "https://sephora.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
      {
        store: "Ulta",
        price: 39.99,
        currency: "EUR",
        url: "https://ulta.com/product",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "product-2",
    name: "Matte Liquid Lipstick - Ruby Red",
    brand: "ColorPop",
    description:
      "Long-lasting matte liquid lipstick that provides full coverage and comfortable wear.",
    category: "makeup",
    subcategory: "lips",
    targetGender: "women",
    image:
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&h=300&fit=crop",
    ],
    ingredients: ["Dimethicone", "Cyclopentasiloxane", "Kaolin", "Iron Oxides"],
    suitableFor: {
      skinTypes: ["normal", "oily", "combination", "dry"],
      skinTones: ["light", "medium", "tan", "deep"],
      concerns: [],
    },
    priceComparison: [
      {
        store: "ColorPop",
        price: 8,
        currency: "EUR",
        url: "https://colourpop.com/product",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.2,
    reviewCount: 89,
  },
  {
    id: "product-3",
    name: "Men's Energizing Face Wash",
    brand: "Bulldog",
    description:
      "Refreshing face wash designed for men with natural ingredients. Removes dirt and oil without over-drying.",
    category: "skincare",
    subcategory: "cleansers",
    targetGender: "men",
    image:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300&h=300&fit=crop",
    ],
    ingredients: ["Green Tea", "Aloe Vera", "Green Algae", "Konjac Mannan"],
    suitableFor: {
      skinTypes: ["oily", "normal", "combination"],
      skinTones: ["fair", "light", "medium", "tan", "deep", "dark"],
      concerns: ["oiliness", "acne"],
    },
    priceComparison: [
      {
        store: "Amazon",
        price: 12.99,
        currency: "EUR",
        url: "https://amazon.com/product",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.6,
    reviewCount: 342,
  },
  {
    id: "product-4",
    name: "Vitamin C Brightening Cream",
    brand: "The Ordinary",
    description:
      "Powerful vitamin C formula that brightens skin tone and reduces dark spots. Suitable for all genders.",
    category: "skincare",
    subcategory: "moisturizers",
    targetGender: "unisex",
    image:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop",
    ],
    ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid", "Hyaluronic Acid"],
    suitableFor: {
      skinTypes: ["normal", "dry", "combination"],
      skinTones: ["fair", "light", "medium", "tan", "deep", "dark"],
      concerns: ["dark_spots", "aging", "dryness"],
    },
    priceComparison: [
      {
        store: "Sephora",
        price: 25.99,
        currency: "EUR",
        url: "https://sephora.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.4,
    reviewCount: 267,
  },
  {
    id: "product-5",
    name: "Long-Wear Foundation SPF 15",
    brand: "Estée Lauder",
    description:
      "Full coverage foundation that lasts all day with SPF protection. Perfect for special occasions.",
    category: "makeup",
    subcategory: "face",
    targetGender: "women",
    image:
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=300&h=300&fit=crop",
    ],
    ingredients: ["Titanium Dioxide", "Zinc Oxide", "Dimethicone", "Glycerin"],
    suitableFor: {
      skinTypes: ["normal", "dry", "combination"],
      skinTones: ["fair", "light", "medium", "tan", "deep"],
      concerns: [],
    },
    priceComparison: [
      {
        store: "Macy's",
        price: 52,
        currency: "EUR",
        url: "https://macys.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.7,
    reviewCount: 892,
  },
  {
    id: "product-6",
    name: "Men's Beard Oil - Cedarwood",
    brand: "Jack Black",
    description:
      "Premium beard oil that softens, conditions, and adds shine to facial hair. Natural cedarwood scent.",
    category: "haircare",
    subcategory: "styling",
    targetGender: "men",
    image:
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=300&h=300&fit=crop",
    ],
    ingredients: [
      "Argan Oil",
      "Jojoba Oil",
      "Cedarwood Essential Oil",
      "Vitamin E",
    ],
    suitableFor: {
      skinTypes: ["normal", "dry", "sensitive"],
      concerns: [],
    },
    priceComparison: [
      {
        store: "Amazon",
        price: 18.5,
        currency: "EUR",
        url: "https://amazon.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: "product-7",
    name: "Retinol Night Serum",
    brand: "CeraVe",
    description:
      "Anti-aging night serum with encapsulated retinol to reduce fine lines and improve skin texture.",
    category: "skincare",
    subcategory: "serums",
    targetGender: "unisex",
    image:
      "https://images.unsplash.com/photo-1571689935459-80c604a28bcb?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571689935459-80c604a28bcb?w=300&h=300&fit=crop",
    ],
    ingredients: ["Retinol", "Ceramides", "Hyaluronic Acid", "Niacinamide"],
    suitableFor: {
      skinTypes: ["normal", "dry", "combination"],
      skinTones: ["fair", "light", "medium", "tan", "deep", "dark"],
      concerns: ["aging", "dryness"],
    },
    priceComparison: [
      {
        store: "Ulta",
        price: 19.99,
        currency: "EUR",
        url: "https://ulta.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.5,
    reviewCount: 423,
  },
  {
    id: "product-8",
    name: "Waterproof Mascara - Volume & Length",
    brand: "Maybelline",
    description:
      "Waterproof mascara that delivers dramatic volume and length. Lasts all day without smudging.",
    category: "makeup",
    subcategory: "eyes",
    targetGender: "women",
    image:
      "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=300&h=300&fit=crop",
    ],
    ingredients: ["Beeswax", "Carnauba Wax", "Paraffin", "Glycerin"],
    suitableFor: {
      skinTypes: ["normal", "oily", "sensitive"],
      concerns: [],
    },
    priceComparison: [
      {
        store: "Drugstore",
        price: 9.99,
        currency: "EUR",
        url: "https://drugstore.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.3,
    reviewCount: 1245,
  },
  {
    id: "product-9",
    name: "Men's Charcoal Face Scrub",
    brand: "Nivea Men",
    description:
      "Deep cleansing face scrub with activated charcoal. Removes impurities and prevents breakouts.",
    category: "skincare",
    subcategory: "cleansers",
    targetGender: "men",
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop",
    ],
    ingredients: [
      "Activated Charcoal",
      "Salicylic Acid",
      "Menthol",
      "Glycerin",
    ],
    suitableFor: {
      skinTypes: ["oily", "combination", "normal"],
      concerns: ["acne", "oiliness", "large_pores"],
    },
    priceComparison: [
      {
        store: "Amazon",
        price: 7.99,
        currency: "EUR",
        url: "https://amazon.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.4,
    reviewCount: 567,
  },
  {
    id: "product-10",
    name: "Rose Water Facial Mist",
    brand: "Mario Badescu",
    description:
      "Refreshing rose water spray that hydrates, tones, and revitalizes skin throughout the day.",
    category: "skincare",
    subcategory: "toners",
    targetGender: "women",
    image:
      "https://images.unsplash.com/photo-1556229010-aa3cdf8511e7?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556229010-aa3cdf8511e7?w=300&h=300&fit=crop",
    ],
    ingredients: ["Rose Water", "Aloe Vera", "Gardenia Extract", "Witch Hazel"],
    suitableFor: {
      skinTypes: ["dry", "normal", "sensitive", "combination"],
      concerns: ["dryness", "sensitivity", "redness"],
    },
    priceComparison: [
      {
        store: "Sephora",
        price: 14,
        currency: "EUR",
        url: "https://sephora.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.6,
    reviewCount: 789,
  },
  {
    id: "product-11",
    name: "Men's Anti-Aging Eye Cream",
    brand: "Kiehl's",
    description:
      "Lightweight eye cream formulated for men to reduce dark circles, puffiness, and fine lines.",
    category: "skincare",
    subcategory: "eye_care",
    targetGender: "men",
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop",
    ],
    ingredients: ["Caffeine", "Vitamin E", "Avocado Oil", "Shea Butter"],
    suitableFor: {
      skinTypes: ["normal", "dry", "combination"],
      concerns: ["aging", "dark_spots"],
    },
    priceComparison: [
      {
        store: "Sephora",
        price: 32,
        currency: "EUR",
        url: "https://sephora.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.5,
    reviewCount: 234,
  },
  {
    id: "product-12",
    name: "Volumizing Dry Shampoo",
    brand: "Batiste",
    description:
      "Instant hair refresh with added volume. Perfect for between washes or on-the-go styling.",
    category: "haircare",
    subcategory: "styling",
    targetGender: "women",
    image:
      "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=300&h=300&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=300&h=300&fit=crop",
    ],
    ingredients: ["Butane", "Rice Starch", "Fragrance", "Cetrimonium Chloride"],
    suitableFor: {
      skinTypes: ["normal", "oily"],
      concerns: [],
    },
    priceComparison: [
      {
        store: "Drugstore",
        price: 8.99,
        currency: "EUR",
        url: "https://drugstore.com",
        availability: "in_stock",
        lastUpdated: new Date(),
      },
    ],
    reviews: [],
    influencerReviews: [],
    rating: 4.4,
    reviewCount: 1567,
  },
];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    userId: "user-1",
    user: mockUsers[0],
    productId: "product-1",
    rating: 5,
    title: "Amazing hydration!",
    content:
      "This serum has completely transformed my skin. My face feels so much more hydrated and plump.",
    pros: ["Very hydrating", "Absorbs quickly", "No sticky residue"],
    cons: ["A bit pricey"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-15"),
    helpfulVotes: 12,
    images: [],
  },
  {
    id: "review-2",
    userId: "user-2",
    user: mockUsers[1],
    productId: "product-3",
    rating: 5,
    title: "Best face wash for men!",
    content:
      "Finally found a face wash that actually works. Cleans well without making my skin feel tight.",
    pros: ["Natural ingredients", "Great scent", "Good value"],
    cons: [],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-10"),
    helpfulVotes: 8,
    images: [],
  },
  {
    id: "review-3",
    userId: "user-1",
    user: mockUsers[0],
    productId: "product-2",
    rating: 4,
    title: "Love the color!",
    content:
      "Beautiful ruby red shade that lasts for hours. Can be a bit drying though.",
    pros: ["Long-lasting", "Perfect color", "Affordable"],
    cons: ["Slightly drying"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-20"),
    helpfulVotes: 15,
    images: [],
  },
  {
    id: "review-4",
    userId: "user-3",
    user: mockUsers[2],
    productId: "product-4",
    rating: 5,
    title: "Brightened my dark spots",
    content:
      "After 3 weeks of use, I noticed significant improvement in my dark spots. Very happy with this purchase!",
    pros: ["Effective", "Gentle formula", "Works for sensitive skin"],
    cons: ["Takes time to see results"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-01"),
    helpfulVotes: 22,
    images: [],
  },
  {
    id: "review-5",
    userId: "user-2",
    user: mockUsers[1],
    productId: "product-6",
    rating: 5,
    title: "Beard game changer",
    content:
      "My beard has never looked better. Soft, manageable, and smells amazing.",
    pros: ["Great scent", "Softens beard", "Natural ingredients"],
    cons: ["Wish bottle was bigger"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-25"),
    helpfulVotes: 18,
    images: [],
  },
  {
    id: "review-6",
    userId: "user-1",
    user: mockUsers[0],
    productId: "product-5",
    rating: 4,
    title: "Great coverage",
    content:
      "Covers really well and lasts all day. Just wish they had more shade options.",
    pros: ["Full coverage", "SPF protection", "Long-lasting"],
    cons: ["Limited shades", "Expensive"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-05"),
    helpfulVotes: 25,
    images: [],
  },
  {
    id: "review-7",
    userId: "user-3",
    user: mockUsers[2],
    productId: "product-7",
    rating: 5,
    title: "Retinol that actually works",
    content:
      "Been using for 2 months and my fine lines are noticeably reduced. No irritation!",
    pros: ["Effective", "No irritation", "Great price"],
    cons: [],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-18"),
    helpfulVotes: 31,
    images: [],
  },
  {
    id: "review-8",
    userId: "user-1",
    user: mockUsers[0],
    productId: "product-8",
    rating: 4,
    title: "Stays put all day",
    content:
      "Truly waterproof and gives great volume. Just a tiny bit clumpy if you apply too much.",
    pros: ["Waterproof", "Volumizing", "Affordable"],
    cons: ["Can clump"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-08"),
    helpfulVotes: 12,
    images: [],
  },
  {
    id: "review-9",
    userId: "user-2",
    user: mockUsers[1],
    productId: "product-9",
    rating: 4,
    title: "Deep clean feeling",
    content:
      "Leaves my face feeling really clean. The charcoal does a great job removing oil.",
    pros: ["Deep cleansing", "Removes blackheads", "Refreshing"],
    cons: ["Can be harsh if used daily"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-30"),
    helpfulVotes: 9,
    images: [],
  },
  {
    id: "review-10",
    userId: "user-3",
    user: mockUsers[2],
    productId: "product-10",
    rating: 5,
    title: "So refreshing!",
    content:
      "Perfect for midday refresh. The rose scent is calming and my skin feels instantly hydrated.",
    pros: ["Refreshing", "Nice scent", "Portable"],
    cons: [],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-12"),
    helpfulVotes: 14,
    images: [],
  },
  {
    id: "review-11",
    userId: "user-2",
    user: mockUsers[1],
    productId: "product-11",
    rating: 4,
    title: "Reduces puffiness",
    content: "Noticed less puffiness in the mornings. Good product but pricey.",
    pros: ["Reduces puffiness", "Lightweight", "Absorbs quickly"],
    cons: ["Expensive"],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-02-03"),
    helpfulVotes: 7,
    images: [],
  },
  {
    id: "review-12",
    userId: "user-1",
    user: mockUsers[0],
    productId: "product-12",
    rating: 5,
    title: "Holy grail dry shampoo",
    content:
      "Best dry shampoo I've ever used. Adds volume and makes my hair look freshly washed.",
    pros: ["Adds volume", "Fresh scent", "Easy to use"],
    cons: [],
    wouldRecommend: true,
    verifiedPurchase: true,
    createdAt: new Date("2024-01-28"),
    helpfulVotes: 28,
    images: [],
  },
];

export const mockInfluencerReviews: InfluencerReview[] = [
  {
    id: "inf-review-1",
    influencerId: "influencer-1",
    influencer: mockInfluencers[0],
    productId: "product-1",
    rating: 4,
    title: "Great for dry skin types",
    description:
      "I tested this serum for 2 weeks and noticed significant improvement in hydration levels.",
    videoUrl: "https://youtube.com/watch?v=example",
    socialMediaUrls: ["https://instagram.com/p/example"],
    createdAt: new Date("2024-01-10"),
    engagement: {
      views: 15000,
      likes: 890,
      shares: 45,
    },
  },
];
